# src: .textlint/dict/prh-my-settings.yml
#
##  @(#) : textlint prh dictionary / atsushifx's add-on
#
# @version 1.0.0
# @author  atsushifx <atsushifx@gmail.com>
# @since   2025-04-17
# @license MIT
#
# @desc<<
#
# textlint prh user dictionary for custom proofreading rules.
# Intended to complement shared base dictionary.
#
#<<

## dict start
rules:

## end of dict
